[basic]
apiport = 8082
apiroot = "/api/data/v1/consumer"
devmode = false
dynamicconfig = false
inswarm = false
isapibody = false
isapirate = false
isapitimeout = false
prof = false
service = "arc-consumer"
zone = "default"

[log]
graylog = ""
level = "INFO"
path = ""

[trace]
jaegerCollector = "http://ip:14268"
jaegerQuery = "jaeger-query:16686"

[service]
device_host = "localhost"
enable_crc_check = true
goroutine_count = 8
host = "127.0.0.1"
keepalive = 60000
net_type = "tcp"
port = 8972
proxy_timealign = true

[grpc]
enable = true
server = "localhost:8081"
